<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\FluentEmail.Core\FluentEmail.Core.csproj" />
    <ProjectReference Include="..\..\src\Senders\FluentEmail.Smtp\FluentEmail.Smtp.csproj" />
    <ProjectReference Include="..\..\src\Senders\FluentEmail.MailKit\FluentEmail.MailKit.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="EmailTemplates\test-embedded.txt" />
    <EmbeddedResource Include="test-embedded.txt" />
    <None Update="logotest.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="test-binary.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="AwesomeAssertions" Version="9.5.0" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Update="xunit.v3" Version="3.2.2" />
  </ItemGroup>

</Project>
