<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Send emails via Azure Email Communication Services API</Description>
        <AssemblyTitle>Fluent Email - Azure Email</AssemblyTitle>
        <PackageTags>$(PackageTags);azureemail</PackageTags>
        <Version>$(Version)</Version>
        <PackageId>jcamp.$(AssemblyName)</PackageId>
        <Product>jcamp.$(AssemblyName)</Product>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\FluentEmail.Core\FluentEmail.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
      <PackageReference Include="System.Text.Json" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.301" />
    </ItemGroup>

</Project>
