<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Send emails via Postmark using their REST API</Description>
        <AssemblyTitle>Fluent Email - Postmark</AssemblyTitle>
        <PackageTags>$(PackageTags);postmark</PackageTags>
        <PackageId>jcamp.$(AssemblyName)</PackageId>
        <Product>jcamp.$(AssemblyName)</Product>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\FluentEmail.Core\FluentEmail.Core.csproj" />
        <PackageReference Include="Postmark" Version="5.4.1" />
		<PackageReference Include="System.Text.Json" Version="10.0.10" />
    </ItemGroup>

	<ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.301" />
    </ItemGroup>

</Project>
