<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Description>Send emails via Microsoft Graph API</Description>
		<AssemblyTitle>Fluent Email - Graph</AssemblyTitle>
		<PackageTags>$(PackageTags);graph</PackageTags>
		<NoWarn>NU5104</NoWarn>
		<PackageId>jcamp.$(AssemblyName)</PackageId>
		<Product>jcamp.$(AssemblyName)</Product>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Graph" Version="4.54.0" />
		<PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.7" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.84.0" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="System.Text.Json" Version="8.0.6" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="System.Text.Json" Version="9.0.16" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="System.Text.Json" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\FluentEmail.Core\FluentEmail.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.300" />
	</ItemGroup>

</Project>
