<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Send emails to Mailtrap. Uses FluentEmail.Smtp for delivery.</Description>
    <AssemblyTitle>Fluent Email - MailTrap</AssemblyTitle>
    <Authors>Luke Lowrey;Ben Cull;Anthony Zigenbine;Github Contributors</Authors>
    <PackageTags>$(PackageTags);mailtrap</PackageTags>
    <PackageId>jcamp.$(AssemblyName)</PackageId>
    <Product>jcamp.$(AssemblyName)</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentEmail.Smtp\FluentEmail.Smtp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.300" />
  </ItemGroup>

</Project>
