<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Send emails via MailPace using their REST API</Description>
        <AssemblyTitle>Fluent Email - MailPace</AssemblyTitle>
        <PackageTags>$(PackageTags);mailpace</PackageTags>
        <PackageId>jcamp.$(AssemblyName)</PackageId>
        <Product>jcamp.$(AssemblyName)</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\FluentEmail.Core\FluentEmail.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.300" />
    </ItemGroup>

</Project>