<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Renderers\FluentEmail.Bootstrap\FluentEmail.Bootstrap.csproj" />
    <ProjectReference Include="..\..\src\Renderers\FluentEmail.Liquid\FluentEmail.Liquid.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Verify.XunitV3" Version="31.28.0" />
	<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.10" />
	<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.10" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="AwesomeAssertions" Version="9.5.0" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Update="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>
