<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Renderers\FluentEmail.Bootstrap\FluentEmail.Bootstrap.csproj" />
    <ProjectReference Include="..\..\src\Renderers\FluentEmail.Liquid\FluentEmail.Liquid.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.21" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="8.0.0" />
    <PackageReference Include="Verify.XunitV3" Version="31.0.3" />
  </ItemGroup>
  
</Project>
